version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "06:17"
      timezone: Europe/Berlin
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns: ["*"]
